### PR TITLE
Update README.md / setup instructions and process

### PR DESCRIPTION
**Pull request by GeneralPoxter**

### CODE REVIEW

**Comment by EntilZha** [comment]
LGTM, aside from keeping the instructions for elastic search around.

**Comment by GeneralPoxter** [comment]
All right, added that back in.

**Comment by EntilZha** [comment]
Ya that would be helpful to add. Its mainly needed if you want to run the ES model, otherwise optional

**Comment by GeneralPoxter** [comment]
All right done.

**Pull request merged**
